
language: kotlin
stages:
  - name: build
before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 11.0.12-open
  - sdk use java 11.0.12-open
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
jobs:
  include:
    - stage: build
      script:
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
        - export JAVA_HOME=$HOME/openjdk11
        - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
        - "./gradlew --stacktrace clean build"
      before_install:
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
